# Generated by Django 5.1.6 on 2025-04-24 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=100)),
                ('main_industry', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('business_model', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('market_segment', models.CharField(max_length=100)),
                ('generated_ideas', models.TextField()),
                ('selected_problem', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'idea_log',
            },
        ),
        migrations.CreateModel(
            name='industry_mapping',
            fields=[
                ('industry_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'industry_mapping',
            },
        ),
        migrations.CreateModel(
            name='main_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_industry',
            },
        ),
        migrations.CreateModel(
            name='user_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=100)),
                ('main_industry', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('business_model', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('market_segment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_selection',
            },
        ),
    ]
