# Generated by Django 5.1.6 on 2025-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_industry_mapping_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=100)),
                ('main_industry', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('business_model', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('market_segment', models.CharField(max_length=100)),
                ('generated_ideas', models.TextField()),
                ('selected_problem', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idea_log',
            },
        ),
    ]
